### ISSUE TITLE
Error: No module named emd

### ISSUE THREAD

**Issue by abenjak** [broadinstitute/PhylogicNDT#11]
Hello,
I installed PhylogicNDT on Docker as instructed, but PhylogicNDT.py exits with:
`root@21913eaf8cc6:/phylogicndt# ./PhylogicNDT.py --help`
`INFO:root:Using fast logsumexp`
`/phylogicndt/BuildTree/build_tree_log.log`
`Traceback (most recent call last):`
  `File "./PhylogicNDT.py", line 19, in <module>`
    `import BuildTree.CellPopulation`
  `File "/phylogicndt/BuildTree/CellPopulation.py", line 6, in <module>`
    `from .BuildTreeEngine import BuildTreeEngine`
  `File "/phylogicndt/BuildTree/BuildTreeEngine.py", line 7, in <module>`
    `import ShuffleMutations`
  `File "/phylogicndt/BuildTree/ShuffleMutations.py", line 4, in <module>`
    `from emd import emd`
`ImportError: No module named emd`

The same happens with the local installation.
Running on Linux Mint 19.1.

Best regards,
Andrej

**Comment by abenjak** [comment]
It works with Singularity.
