### ISSUE TITLE
out of bounds error when running SinglePatientTiming

### ISSUE THREAD

**Issue by shwong-tw** [broadinstitute/PhylogicNDT#21]
Dear developer,

When running SinglePatientTiming, I encounter an error "*** ValueError: ValueError("'axis' entry is out of bounds",)"

It came from Line 548 in PhylogicNDT/SinglePatientTiming/TimingEngine.py
get_p2_dist_for_gain() -> mut_p2_dist += np.sum(mut.log_mult_dist, 1)

I would like to know whether mut.log_mult_dist issupposed to be an 1D array?
In that case is it safe that I just modify it to mut_p2_dist += np.sum(mut.log_mult_dist, 0) and continue with downstream analysis?

Thank you very much :)

**Comment by iglc** [comment]
Hi,

Can you share your cmdline? Are you running multisample analysis?

Thanks!

**Comment by shwong-tw** [comment]
Hi,

Thank you for the prompt reply :)
Yes, I am doing multisample analysis in conda environment.
The parameters I set were:
For Clustering+BuildTree: `python ${PhylogicNDT_DIR}/PhylogicNDT.py Cluster -i Patient -sif ${PhylogicNDT_DIR}/input/Patient_Cluster.sif -rb --impute`
For SinglePatientTiming: `python ${PhylogicNDT_DIR}/PhylogicNDT.py SinglePatientTiming -i Patient -sif ${PhylogicNDT_DIR}/input/Patient_Timing.sif`
Where Patient_Timing.sif used the output from Clustering (.mut_ccfs.txt) as its maf_fn input

Please let me know if there wer any further information I can provide.
Thanks a lot!

**Comment by shwong-tw** [comment]
btw, I just reproduced the error on my Ubuntu machine, please find details below:
```
${PhylogicNDT_DIR}/phylogicndt.log
Traceback (most recent call last):
  File "${PhylogicNDT_DIR}/PhylogicNDT.py", line 520, in <module>
    args.func(args)
  File "${PhylogicNDT_DIR}/SinglePatientTiming/SinglePatientTiming.py", line 50, in run_tool
    timing_engine = TimingEngine.TimingEngine(patient_data, min_supporting_muts=args.min_supporting_muts)
  File "${PhylogicNDT_DIR}/SinglePatientTiming/TimingEngine.py", line 38, in __init__
    self.call_wgd()
  File "${PhylogicNDT_DIR}/SinglePatientTiming/TimingEngine.py", line 111, in call_wgd
    sample.concordant_WGD.get_pi_dist()
  File "${PhylogicNDT_DIR}/SinglePatientTiming/TimingEngine.py", line 428, in get_pi_dist
    eve.get_pi_dist_for_gain()
  File "${PhylogicNDT_DIR}/SinglePatientTiming/TimingEngine.py", line 560, in get_pi_dist_for_gain
    p2_real = self.get_p2_dist_for_gain()
  File "${PhylogicNDT_DIR}/SinglePatientTiming/TimingEngine.py", line 548, in get_p2_dist_for_gain
    mut_p2_dist += np.sum(mut.log_mult_dist, 1)
  File "/home/wong/software-home/PythonEnv/envs/Conda2/lib/python2.7/site-packages/numpy/core/fromnumeric.py", line 1848, in sum
    out=out, **kwargs)
  File "/home/wong/software-home/PythonEnv/envs/Conda2/lib/python2.7/site-packages/numpy/core/_methods.py", line 32, in _sum
    return umr_sum(a, axis, dtype, out, keepdims)
ValueError: 'axis' entry is out of bounds
```

**Comment by jcha40** [comment]
Hello,

I wasn't able to reproduce the error, but maybe the latest version might help. If it still doesn't work, it's likely that something is wrong with the input files.

**Comment by shwong-tw** [comment]
Hi,

Thanks for looking into it! I have tried the latest version and the error msg remains.

Would it be possible that you would offer a seg_fn that fits ExampleData, given that including seg_fn had worked in your case. I will try to reproduce it in my machine and see what were the differences :)
