### ISSUE TITLE
ABSOLUTE for CCF

### ISSUE THREAD

**Issue by mkinnaman** [broadinstitute/PhylogicNDT#29]
Hi - I am trying to use Absolute to make the CCF histograms required for the algorithm.

I have both allele-specific copy number and total copy number but I cant figure out how to properly format the inputs for absolute. 

There is no example outputs from hapseg I could find to see if I could somehow fit my data to that format and I couldn't find an answer for what to put for num_probes with WGS data. My understanding is that segment_mean is log2 ratio.

Would I be fine just using the pipeline without supplying the histogram info as is mentioned in the instruction or better to get histogram through absolute?

**Comment by mkinnaman** [comment]
As a follow up I tried running with having Phylogic calculate the CCF's and I was unsure what command to enter and how to format the maf files. The first run I didnt enter the headers for the CCF bins and it threw an error due to that. The second time I added the headers for the CCF bins and left the values blank but got the following error:

Traceback (most recent call last):
  File "./PhylogicNDT.py", line 393, in <module>
    args.func(args)
  File "/phylogicndt/Cluster/Cluster.py", line 50, in run_tool
    purity=purity)
  File "/phylogicndt/data/Patient.py", line 115, in addSample
    purity=purity, timepoint_value=timepoint_value)
  File "/phylogicndt/data/Sample.py", line 89, in __init__
    _additional_muts=_additional_muts)  # a list of SomMutation objects
  File "/phylogicndt/data/Sample.py", line 126, in _load_sample_ccf
    mut_with_ccf_dat = self._read_ccf_from_txt(filen)
  File "/phylogicndt/data/Sample.py", line 290, in _read_ccf_from_txt
    ccf = [float(spl[x]) for x in ccf_bins_location]
IndexError: list index out of range

I appreciate any thoughts.

Thanks,
Michael

**Comment by jcha40** [comment]
Hello, 

If you clone the latest update, you should be able to get PhylogicNDT to calculate the CCFs by setting the `--maf_input_type` flag to `calc_ccf`. PhylogicNDT requires sample purity and local copy number for each mutation (column names `local_cn_a1` and `local_cn_a2`) in order to calculate the CCF.

**Comment by mkinnaman** [comment]
Thanks for pushing this update through - I can now run the cluster command without issue. I am still running into a couple of issues which I feel are something to with formatting but I cant pinpoint the issue.

When I try to run the combined cluster and buildtree command I am getting this error:
`Traceback (most recent call last):
  File "./PhylogicNDT.py", line 515, in <module>
    args.func(args)
  File "/lila/home/kinnamam/miniconda3/envs/phylogic/PhylogicNDT/Cluster/Cluster.py", line 114, in run_tool
    BuildTree.BuildTree.run_tool(args)
  File "/lila/home/kinnamam/miniconda3/envs/phylogic/PhylogicNDT/BuildTree/BuildTree.py", line 17, in run_tool
    parse_sif_file(args.sif, args.mutation_ccf_file, patient_data)
  File "/lila/home/kinnamam/miniconda3/envs/phylogic/PhylogicNDT/BuildTree/BuildTree.py", line 64, in parse_sif_file
    timepoint = float(values[header['timepoint']])
KeyError: 'timepoint'`

My sif file was modeled after the example file so I am not sure why this error is popping up. I have attached my sif file for your review.

The second issue I am having is that I had to remove the paths to my cn_seg file from the sif file to get the cluster function to work. If I leave them in I get the following error, again looking related to formatting:
`Traceback (most recent call last):
  File "./PhylogicNDT.py", line 515, in <module>
    args.func(args)
  File "/lila/home/kinnamam/miniconda3/envs/phylogic/PhylogicNDT/Cluster/Cluster.py", line 54, in run_tool
    purity=purity, input_type=args.maf_input_type)
  File "/lila/home/kinnamam/miniconda3/envs/phylogic/PhylogicNDT/data/Patient.py", line 148, in addSample
    purity=purity, timepoint_value=timepoint_value)
  File "/lila/home/kinnamam/miniconda3/envs/phylogic/PhylogicNDT/data/Sample.py", line 94, in __init__
    self.CnProfile = self._resolve_CnEvents(seg_file, input_type=seg_input_type)
  File "/lila/home/kinnamam/miniconda3/envs/phylogic/PhylogicNDT/data/Sample.py", line 534, in _resolve_CnEvents
    raise NotImplementedError('Input file type not supported')
NotImplementedError: Input file type not supported`

I have attached a seg file as well from my sample set.

Finally- is there a way to set a minimum for cluster size when running the clustering command - like for example, a cluster has to have a minimum of 10 mutations to be considered?


[OSCE1_input.sif.txt](https://github.com/broadinstitute/PhylogicNDT/files/4352069/OSCE1_input.sif.txt)
[T2-4_CN_Seg.txt](https://github.com/broadinstitute/PhylogicNDT/files/4352070/T2-4_CN_Seg.txt)

**Comment by lincj1994** [comment]
Hi. I'm wondering if you have solved this issue. If so, could you please provide the example input and code for PhylogicNDT Cluster to calculate CCF? Thank you.

**Comment by lincj1994** [comment]
> Hello,
> 
> If you clone the latest update, you should be able to get PhylogicNDT to calculate the CCF input histograms without ABSOLUTE input by setting the `--maf_input_type` flag to `calc_ccf`. PhylogicNDT requires sample purity and local copy number for each mutation (column names `local_cn_a1` and `local_cn_a2`) in order to calculate the CCF.

Hi. I'm wondering which one is major cn of local_cn_a1 and local_cn_a2?

**Comment by THT-sleepy** [comment]
> > Hello,
> > If you clone the latest update, you should be able to get PhylogicNDT to calculate the CCF input histograms without ABSOLUTE input by setting the `--maf_input_type` flag to `calc_ccf`. PhylogicNDT requires sample purity and local copy number for each mutation (column names `local_cn_a1` and `local_cn_a2`) in order to calculate the CCF.
> 
> Hi. I'm wondering which one is major cn of local_cn_a1 and local_cn_a2?
Did you figured out this ?

**Comment by THT-sleepy** [comment]
> > Hello,
> > If you clone the latest update, you should be able to get PhylogicNDT to calculate the CCF input histograms without ABSOLUTE input by setting the `--maf_input_type` flag to `calc_ccf`. PhylogicNDT requires sample purity and local copy number for each mutation (column names `local_cn_a1` and `local_cn_a2`) in order to calculate the CCF.
> 
> Hi. I'm wondering which one is major cn of local_cn_a1 and local_cn_a2?

Did you figure it out ?
