### ISSUE TITLE
Cannot run with example data

### ISSUE THREAD

**Issue by SebastianHollizeck** [broadinstitute/PhylogicNDT#5]
Hey,

I tried to run this with the example data provided, but it crashes with 

```
./PhylogicNDT.py Cluster -i Patient_ID --sample_information ExampleData/ExampleSamples/MySimulation_input.sif 
Namespace(Delete_Blacklist=False, Pi_k_mu=3, Pi_k_r=3, PoN='false', artifact_blacklist='./data/supplement_data/Blacklist_SNVs.txt', artifact_whitelist='', buildtree=False, cancer_type='All_cancer', driver_genes_file='./data/supplement_data/Driver_genes_v1.0.txt', func=<function run_tool at 0x7f561740dde8>, gistic_fn=None, grid_size=101, html=True, impute_missing=False, indiv_id='Patient_ID', iter=250, maf=False, min_cov=8, n_samples=0, order_by_timepoint=False, sample_data=None, scale=False, sif='ExampleData/ExampleSamples/MySimulation_input.sif', time_points=None, treatment_data=None, tumor_size=None, use_indels=False)
Traceback (most recent call last):
  File "./PhylogicNDT.py", line 342, in <module>
    args.func(args)
  File "/home/shollizeck/PhylogicNDT/Cluster/Cluster.py", line 17, in run_tool
    import ClusterEngine
  File "/home/shollizeck/PhylogicNDT/Cluster/ClusterEngine.py", line 11, in <module>
    import DpEngine
  File "/home/shollizeck/PhylogicNDT/Cluster/DpEngine.py", line 9, in <module>
    import sklearn.manifold as manifold
ImportError: No module named sklearn.manifold
```
The help works though. So i can see the -h output

Would be very interested in using this

Cheers,
Sebastian

**Comment by jcha40** [comment]
Hello,

In order to run PhylogicNDT, you first need to install all of its dependencies by following either the "Manual Install" section or the "Docker Install" section of the readme.

**Comment by SebastianHollizeck** [comment]
I did follow the manual install instructions, and as I am working on a HPC our sysadmin does not allow docker.

**Comment by iglc** [comment]
Hi, 
Make sure sklearn (and .manifold) is installed on the cluster (not just on log-in node) or use venv. Talk to your sysadmin.

**Comment by SebastianHollizeck** [comment]
got it to work with singularity instead
