### ISSUE TITLE
About SinglePatientTiming demo

### ISSUE THREAD

**Issue by RetGiraffe11235** [broadinstitute/PhylogicNDT#67]
Hi Developer,

Thank you for developing such a valuable tool.
I apologize for my limited understanding, but could you guide me on how to run SinglePatientTiming using the example data? I tried to execute it using the SegFile in ExampleData, but it wasn't successful. It would be greatly appreciated if you could provide sample data specifically for SinglePatientTiming.
Thank you for your great effort in maintaining this tool.

Best,
Tomoki

**Comment by iglc** [comment]
Please first run the Clustering and Build tree tools.

**Comment by TomokiMotegi** [comment]
Hi iglc,
Thank you for your reply. I have completed the clustering and constructed the tree via singularity using original samples. Then, I made seg files from `get_CN_Absolute.Phylogic_SinglePatientTiming.R` and I tried to run Timing but encountered an issue. The error message is below.
"Traceback (most recent call last):
  File "/phylogicndt/PhylogicNDT.py", line 515, in <module>
    args.func(args)
  File "/phylogicndt/SinglePatientTiming/SinglePatientTiming.py", line 28, in run_tool
    purity=purity)
  File "/phylogicndt/data/Patient.py", line 148, in addSample
    purity=purity, timepoint_value=timepoint_value)
  File "/phylogicndt/data/Sample.py", line 92, in __init__
    _additional_muts=_additional_muts)  # a list of SomMutation objects
  File "/phylogicndt/data/Sample.py", line 139, in _load_sample_ccf
    mut_with_ccf_dat = self._read_post_clustering_results(filen)
  File "/phylogicndt/data/Sample.py", line 219, in _read_post_clustering_results
    sample_id = values[header['Sample_ID']]
UnboundLocalError: local variable 'header' referenced before assignment"

Could you please provide guidance on resolving this error?
