### ISSUE TITLE
IndexError

### ISSUE THREAD

**Issue by SebastianHollizeck** [broadinstitute/PhylogicNDT#9]
Hey,

with my command

```
~/PhylogicNDT/PhylogicNDT.py Cluster -i sample_id -sif CA99_input.sif -rb
```

I get 
```
Traceback (most recent call last):
  File "/home/shollizeck/PhylogicNDT/PhylogicNDT.py", line 342, in <module>
    args.func(args)
  File "/home/shollizeck/PhylogicNDT/Cluster/Cluster.py", line 91, in run_tool
    phylogicoutput.write_patient_mut_ccfs(patient_data, cluster_ccfs)
  File "/home/shollizeck/PhylogicNDT/output/PhylogicOutput.py", line 829, in write_patient_mut_ccfs
    mut_mean, mut_high, mut_low = self._get_mean_high_low(np.array(mut.ccf_1d))
  File "/home/shollizeck/PhylogicNDT/output/PhylogicOutput.py", line 878, in _get_mean_high_low
    elif low == 0 or ccf[high + 1] > ccf[low - 1]:
IndexError: index 5051 is out of bounds for axis 0 with size 101
```

can you help me fix that?

Cheers,
Sebastian

**Comment by iglc** [comment]
Please check if your input is malformated. Can you provide a header here?

**Comment by SebastianHollizeck** [comment]
These are the files I used

```
[shollizeck@vmpr-res-cluster1 test_phylogicNDT]$ cat CA99_input.sif
 sample_id	maf_fn	seg_fn	purity	timepoint
 CA9911	CA99-11.tsv		0.71	0
 CA9926	CA99-26.tsv		0.60	0
 CA9931	CA99-31.tsv		0.15	0
 CA9941	CA99-41.tsv		0.21	0
 CA9947	CA99-47.tsv		0.45	0
 CA9955	CA99-55.tsv		0.37	0
 CA9957	CA99-57.tsv		0.60	0
 CA9959	CA99-57.tsv		0.66	0
```

and 
```
[shollizeck@vmpr-res-cluster1 test_phylogicNDT]$ head CA99-11.tsv
Hugo_Symbol	Chromosome	Start_position	Reference_Allele	Tumor_Seq_Allele2	t_ref_count	t_alt_count	ccf_0.00	ccf_0.01	ccf_0.02	ccf_0.03	ccf_0.04	ccf_0.05	ccf_0.06	ccf_0.07	ccf_0.08	ccf_0.09	ccf_0.10	ccf_0.11	ccf_0.12	ccf_0.13	ccf_0.14	ccf_0.15	ccf_0.16	ccf_0.17	ccf_0.18	ccf_0.19	ccf_0.20	ccf_0.21	ccf_0.22	ccf_0.23	ccf_0.24	ccf_0.25	ccf_0.26	ccf_0.27	ccf_0.28	ccf_0.29	ccf_0.30	ccf_0.31	ccf_0.32	ccf_0.33	ccf_0.34	ccf_0.35	ccf_0.36	ccf_0.37	ccf_0.38	ccf_0.39	ccf_0.40	ccf_0.41	ccf_0.42	ccf_0.43	ccf_0.44	ccf_0.45	ccf_0.46	ccf_0.47	ccf_0.48	ccf_0.49	ccf_0.50	ccf_0.51	ccf_0.52	ccf_0.53	ccf_0.54	ccf_0.55	ccf_0.56	ccf_0.57	ccf_0.58	ccf_0.59	ccf_0.60	ccf_0.61	ccf_0.62	ccf_0.63	ccf_0.64	ccf_0.65	ccf_0.66	ccf_0.67	ccf_0.68	ccf_0.69	ccf_0.70	ccf_0.71	ccf_0.72	ccf_0.73	ccf_0.74	ccf_0.75	ccf_0.76	ccf_0.77	ccf_0.78	ccf_0.79	ccf_0.80	ccf_0.81	ccf_0.82	ccf_0.83	ccf_0.84	ccf_0.85	ccf_0.86	ccf_0.87	ccf_0.88	ccf_0.89	ccf_0.90	ccf_0.91	ccf_0.92	ccf_0.93	ccf_0.94	ccf_0.95	ccf_0.96	ccf_0.97	ccf_0.98	ccf_0.99	ccf_1.00
UNKNOWN	10	107969	T	C	66	1
UNKNOWN	10	168689	C	T	75	0
UNKNOWN	10	387459	A	C	76	1
UNKNOWN	10	414108	G	T	33	0
UNKNOWN	10	430991	T	G	75	0
UNKNOWN	10	493860	T	G	47	0
UNKNOWN	10	541819	C	A	64	0
UNKNOWN	10	548907	G	A	66	0
UNKNOWN	10	551557	T	G	80	0

```

**Comment by iglc** [comment]
You don't seem to have any input CCF values?

**Comment by SebastianHollizeck** [comment]
As the guide said

> the .maf should contain pre-computed raw ccf histograms based on mutations alt/ref count, local copy-number and sample purity (Absolute annotated mafs or .Rdata files are also supported) if the ccf histograms are absent - PhylogicNDT will attempt to compute them from available mutation info as above

I left the ccf values empty

**Comment by iglc** [comment]
But then you need local absolute copy number data for each mutation. Do you
have that?

**Comment by SebastianHollizeck** [comment]
I do have that yes

**Comment by mkinnaman** [comment]
Sorry - to close out this thread - if you have local absolute copy number data - should those be added to the maf file? 2 columns with nmin and and nmaj?
